server:
  port: 9090
  servlet:
    context-path: /     #web启动动时，项目的名称
  tomcat:
    uri-encoding: UTF-8     #配置tomcat的请求编码

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/maple?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  #视图配置
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0


#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.example.*.entity
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#log4j2
logging:
  config: classpath:log4j2.xml