server:
  port: 9090
  servlet:
    context-path: /     #web启动动时，项目的名称
  tomcat:
    uri-encoding: UTF-8     #配置tomcat的请求编码

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/changjiang?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true

    url: jdbc:mysql://localhost:3306/maple?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    druid:
      validationQuery: SELECT 1
      initialSize: 10
      minIdle: 10
      maxActive: 200
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
  #视图配置
  mvc:
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password: 123456

#mybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号隔离
  typeAliasesPackage: com.example.*.entity
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#log4j2
logging:
  config: classpath:log4j2.xml
#是否开启权限
permission:
  open: true

mica:
  xss:
    enabled: true
    path-patterns: /**
    exclude-patterns:
    trim-text: true
    enable-escape: false # clear专用转义，默认关闭
    mode: clear # 模式：clear 清理（默认），escape 转义
    pretty-print: false # clear专用 prettyPrint，默认关闭： 保留换行
